name: Build APK Without Gradlew
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Project
        run: |
          # فك ضغط الملف في مجلد فرعي لضمان التنظيم
          find . -name "*.zip" -exec unzip -o {} -d ./source_code \;
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current

      - name: Build with System Gradle
        run: |
          # البحث عن مكان ملف build.gradle والدخول إليه
          PROJECT_DIR=$(find ./source_code -name "build.gradle" -exec dirname {} \; | head -n 1)
          cd "$PROJECT_DIR"
          # استخدام gradle الخاص بالنظام لبناء الـ APK
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: My-Final-App
          path: "**/*.apk"
          path: "**/*.apk"
