name: Build APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract ZIP
        run: |
          mkdir -p src_code
          find . -name "*.zip" -exec unzip -o {} -d ./src_code \;

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Build
        run: |
          PROJECT_DIR=$(find ./src_code -name "build.gradle" -exec dirname {} \; | head -n 1)
          cd "$PROJECT_DIR"
          # قبول التراخيص تلقائياً وبدء البناء
          yes | sdkmanager --licenses || true
          gradle assembleDebug --stacktrace

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: My-App-APK
          path: "**/*.apk"
